### ISSUE TITLE
bootstrap-collapse.js fehlt!

### ISSUE THREAD

**Issue by PatricB** [VisualPHPUnit/VisualPHPUnit#144]
The nav markup is written for collapse action of bootstrap, but no bootstrap-collapse.js is not inculded!!!

**Comment by localgod** [comment]
I'll look in to this.

**Comment by localgod** [comment]
While not completely ready, check out the [3.x branch](https://github.com/VisualPHPUnit/VisualPHPUnit/tree/3.x). As all my effort is on getting the 3.0 version ready this issue will not be fixed by me. If a pull request with a fix is provided I will be happy to add it to the [2.x branch](https://github.com/VisualPHPUnit/VisualPHPUnit/tree/2.x).

**Comment by localgod** [comment]
There will be no further development on the 2.x branch. Pull request that fixes this bug will merged.
